import { LeftDarkComponent } from "@/common/components/Auth/LeftDarkComponent";
import { CommandIcon } from "@/common/icons";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Expense Tracker - Setting",
  description: "Generated by create next app",
};

export default function SettingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col overflow-auto h-[calc(100%-60px)]">
      <main className="flex flex-1 flex-col h-full gap-8 p-2 md:p-3 lg:flex-row">
        <div className="flex-1 h-full rounded-lg border border-zinc-200 dark:border-zinc-800 flex">
          <LeftDarkComponent />
          <div className="w-full h-full">{children}</div>
        </div>
      </main>
    </div>
  );
}
