import { LeftNavigationBar } from "@/common/components/LeftNavigationBar";
import { TopNavigationBar } from "@/common/components/TopNavigationBar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Expense Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div key="1" className="flex h-full w-full m-auto border-x">
          <LeftNavigationBar />
          <div className="flex flex-col w-full h-full">
            <TopNavigationBar />
            {children}
            <Analytics />
          </div>
        </div>
      </body>
    </html>
  );
}
